### ISSUE TITLE
Broken CLA Link

### ISSUE THREAD

**Issue by achrinza** [strongloop-community/loopback-connector-redis#59]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

The CLA link in [CONTRIBUTING.md](https://github.com/strongloop-community/loopback-connector-redis/blob/1560ed6169c8e7a5e5b8c0dbe2b289080ee9c87b/CONTRIBUTING.md) is broken.

### Link to sample repo to reproduce issue (if bug)

N/A

### Expected result

The CLA link should points to a valid web page.

### Actual result (if bug)

The CLA link points to an non-existent web page:

![image](https://user-images.githubusercontent.com/25147899/70860941-882b0c00-1f62-11ea-996a-d78a8363dc40.png)

**Comment by dhmlau** [comment]
@achrinza, I've disabled CLA check but added DCO checks. Please see my comment in https://github.com/strongloop/loopback-next/issues/4449#issuecomment-576842311. 
Closing as resolved. Thanks.
